package com.koala.app.client;

/**
 * Created by mrsfy on 19-Dec-16.
 */
public enum EventType {
    AUTH, FAVORITES_CLICKED, MESSAGES_CLICKED, SELL_HOUSE_LOCATION_SELECTED, MAP_BOUNDS_CHANGED, LOGOUT_CLICKED, EDIT_HOUSE_CLICKED, REMOVE_HOUSE_CLICKED, MY_OWN_PROPERTIES_CLICKED, SEND_MESSAGE_CLICKED, SELL_HOUSE_CLICKED
}
